#pragma once

#define MATRIX_ROWS 5
#define MATRIX_COLS 14


#define RGB_MATRIX_LED_COUNT 63
#define WS2812_DI_PIN GP28
#define RGB_MATRIX_CENTER { 112, 32 }  
#define WS2812_PIO_PIO1
#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_GRB

// RGB Matrix effects
#define ENABLE_RGB_MATRIX_BREATHING


#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200
#define RGB_MATRIX_STARTUP_VAL 150
#define RGB_DISABLE_TIMEOUT 0