DEFAULT_FOLDER = rp60
PLATFORM = rasberrypi
BOOTLOADER = rp2040

DEBOUNCE_TYPE = sym_defer_g

BOOTMAGIC_ENABLE = yes

NKRO_ENABLE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
WS2812_DRIVER = vendor